version: "3"

networks:
  app-network:
    driver: bridge

services:
  # nuxt:
  #   restart: always
  #   container_name: drewdru_node_local
  #   build:
  #     context: .
  #     dockerfile: compose/node/Dockerfile_dev
  #   # command: nodemon --inspect=0.0.0.0:9229 --nolazy app.js
  #   ports:
  #     - "4000:4000"
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/home/app/drewdru
  #     - /home/app/drewdru/node_modules
  #   depends_on:
  #     - mongo
  #     - redis
  #   networks:
  #     - app-network

  mongo:
    image: mongo:4.2
    container_name: drewdru_mongo_local
    env_file:
      - .env
    command: mongod --port 27017 --storageEngine wiredTiger
    volumes:
      - ./compose/mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  redis:
    image: redis:5.0.12-alpine
    container_name: drewdru_redis_local
    ports:
      - "6379:6379"
    networks:
      - app-network

