services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: ${PG_USER-postgres}
      POSTGRES_PASSWORD: ${PG_PASS-password}
      POSTGRES_DB: ${PG_DB-postgres}
    volumes: 
      - ./.local_data/postgresql:/var/lib/postgresql
    ports:
      - '${PG_LOCAL_PORT-15432}:5432'
    networks:
      - default
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:8-alpine
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
      - --requirepass ${REDIS_PASSWORD-password}
    volumes:
      - ./docs/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - .local_data/redis/data:/data/
    ports:
      - '${REDIS_LOCAL_PORT-16379}:6379'
    logging:
      options:
        max-size: "10m"
        max-file: "3"