services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: ${PG_USER-postgres}
      POSTGRES_PASSWORD: ${PG_PASS-password}
      POSTGRES_DB: ${PG_DB-postgres}
    volumes: 
      - ./.local_data/postgresql:/var/lib/postgresql
    ports:
      - '${PG_LOCAL_PORT-15432}:5432'
    networks:
      - default
    logging:
      options:
        max-size: "10m"
        max-file: "3"