server {
  server_name drewdru.com career.drewdru.com dev.drewdru.com;

  location ~* (.*well-known.*) {
    return 404;
  }

  location = / {
    if ($host = drewdru.com) {
      return 301 /en/welcome;
    }

    if ($host = career.drewdru.com) {
      return 301 /en/cv;
    }

    if ($host = dev.drewdru.com) {
      return 301 /en/projects;
    }
  }

  location / {
    proxy_pass http://127.0.0.1:13000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";    
  }

  # TODO: ADD certs
  listen 443 ssl;
}

server {
  server_name www.drewdru.com;

  # TODO: ADD certs
  listen 443 ssl;

  return 301 https://drewdru.com$request_uri;
}
