export default {
  themeName: 'red',
  body: '#ffffff',
  bodyText: 'red',
  primary: 'red',
  secondary: 'yellow',
  active: '#42b983',
  accent: '#782A2A',
  accentText: 'white',
  error: '#FF5252',
  info: '#2196F3',
  success: '#4CAF50',
  warning: '#FB8C00',
  shadow: '#FF00007F',
  control: '#ffffff',
  controlText: 'red',
};
