export default {
    English: 'English',
    Russian: 'Russian',
    body: 'Body',
    bodyText: 'Body text',
    primary: 'Primary',
    secondary: 'Secondary',
    active: 'Active',
    activeText: 'Active text',
    accent: 'Accent',
    accentText: 'Accent text',
    error: 'Error',
    info: 'Info',
    success: 'Success',
    warning: 'Warning',
    shadow: 'Shadow',
    control: 'Control',
    controlText: 'Control text',
    button: 'Button',
    buttonText: 'Button text',

    January: 'January',
    February: 'February',
    March: 'March',
    April: 'April',
    May: 'May',
    June: 'June',
    July: 'July',
    August: 'August',
    September: 'September',
    October: 'October',
    November: 'November',
    December: 'December',
};
