export default {
    English: 'Английский',
    Russian: 'Русский',
    body: 'Фон',
    bodyText: 'Текст фона',
    primary: 'Основной',
    secondary: 'Дополнительный',
    active: 'Активный',
    activeText: 'Активный текст',
    accent: 'Акцент',
    accentText: 'Текст акцента',
    error: 'Ошибка',
    info: 'Информация',
    success: 'Успех',
    warning: 'Предупреждение',
    shadow: 'Тема',
    control: 'Поле',
    controlText: 'Текст поля',
    button: 'Кнопка',
    buttonText: 'Текст кнопки',
};
